const SET_THEME = "SET_THEME";
const SHOW_PROFILE_TAB = "SHOW_PROFILE_TAB";
const CLOSE_PROFILE_TAB = "CLOSE_PROFILE_TAB";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGIN_CLEAN_ERRORS = "LOGIN_CLEAN_ERRORS";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const SET_AVATAR_REQUEST = "SET_AVATAR_REQUEST";
const SET_AVATAR_SUCCESS = "SET_AVATAR_SUCCESS";
const SET_AVATAR_FAILED = "SET_AVATAR_FAILED";
const SET_AVATAR_CLEAN_ERROR = "SET_AVATAR_CLEAN_ERROR";
const SET_PROMPT = "SET_PROMPT";
const SET_PROMPT_FAILED = "SET_PROMPT_FAILED";
const GET_RESPONSE_REQUEST = "GET_RESPONSE_REQUEST";
const GET_RESPONSE_SUCCESS = "GET_RESPONSE_SUCCESS";
const GET_RESPONSE_FAILED = "GET_RESPONSE_FAILED";
const GET_USERS_REQUEST = "GET_USERS_REQUEST";
const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
const GET_USERS_FAILED = "GET_USERS_FAILED";
const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
const CREATE_USER_FAILED = "CREATE_USER_FAILED";
const CREATE_USER_CLEAN_ERROR = "CREATE_USER_CLEAN_ERROR";
const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const DELETE_USER_FAILED = "DELETE_USER_FAILED";
const DELETE_USER_CLEAN_ERROR = "DELETE_USER_CLEAN_ERROR";
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
const UPDATE_USER_CLEAN_ERROR = "UPDATE_USER_CLEAN_ERROR";
const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST";
const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
const UPDATE_USER_PASSWORD_FAILED = "UPDATE_USER_PASSWORD_FAILED";
const UPDATE_USER_PASSWORD_CLEAN_ERROR = "UPDATE_USER_PASSWORD_CLEAN_ERROR";
const VERIFY_ACCOUNT_REQUEST = "VERIFY_ACCOUNT_REQUEST";
const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
const VERIFY_ACCOUNT_FAILED = "VERIFY_ACCOUNT_FAILED";
const CONTACT_ME_REQUEST = "CONTACT_ME_REQUEST";
const CONTACT_ME_SUCCESS = "CONTACT_ME_SUCCESS";
const CONTACT_ME_FAILED = "CONTACT_ME_FAILED";
const CONTACT_ME_CLEAN_ERROR = "CONTACT_ME_CLEAN_ERROR";
const RECOVER_PASSWORD_REQUEST = "RECOVER_PASSWORD_REQUEST";
const RECOVER_PASSWORD_SUCCESS = "RECOVER_PASSWORD_SUCCESS";
const RECOVER_PASSWORD_FAILED = "RECOVER_PASSWORD_FAILED";
const RECOVER_PASSWORD_CLEAN_ERROR = "RECOVER_PASSWORD_CLEAN_ERROR";
const SET_PASSWORD_REQUEST = "SET_PASSWORD_REQUEST";
const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
const SET_PASSWORD_FAILED = "SET_PASSWORD_FAILED";
const SET_PASSWORD_CLEAN_ERROR = "SET_PASSWORD_CLEAN_ERROR";

export {
  SET_THEME,
  SHOW_PROFILE_TAB,
  CLOSE_PROFILE_TAB,
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGIN_CLEAN_ERRORS,
  LOGOUT_REQUEST,
  SET_AVATAR_REQUEST,
  SET_AVATAR_SUCCESS,
  SET_AVATAR_FAILED,
  SET_AVATAR_CLEAN_ERROR,
  SET_PROMPT,
  SET_PROMPT_FAILED,
  GET_RESPONSE_REQUEST,
  GET_RESPONSE_SUCCESS,
  GET_RESPONSE_FAILED,
  GET_USERS_REQUEST,
  GET_USERS_SUCCESS,
  GET_USERS_FAILED,
  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILED,
  CREATE_USER_CLEAN_ERROR,
  DELETE_USER_REQUEST,
  DELETE_USER_SUCCESS,
  DELETE_USER_FAILED,
  DELETE_USER_CLEAN_ERROR,
  UPDATE_USER_REQUEST,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_FAILED,
  UPDATE_USER_CLEAN_ERROR,
  UPDATE_USER_PASSWORD_REQUEST,
  UPDATE_USER_PASSWORD_SUCCESS,
  UPDATE_USER_PASSWORD_FAILED,
  UPDATE_USER_PASSWORD_CLEAN_ERROR,
  VERIFY_ACCOUNT_REQUEST,
  VERIFY_ACCOUNT_SUCCESS,
  VERIFY_ACCOUNT_FAILED,
  CONTACT_ME_REQUEST,
  CONTACT_ME_SUCCESS,
  CONTACT_ME_FAILED,
  CONTACT_ME_CLEAN_ERROR,
  RECOVER_PASSWORD_REQUEST,
  RECOVER_PASSWORD_SUCCESS,
  RECOVER_PASSWORD_FAILED,
  RECOVER_PASSWORD_CLEAN_ERROR,
  SET_PASSWORD_REQUEST,
  SET_PASSWORD_SUCCESS,
  SET_PASSWORD_FAILED,
  SET_PASSWORD_CLEAN_ERROR,
};
